DROP TABLE IF EXISTS user_flower;
DROP TABLE IF EXISTS flower;
CREATE TABLE flower
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(256) UNIQUE NOT NULL,
    price       REAL                NOT NULL,
    description VARCHAR(1024)       NOT NULL,
    img_link    VARCHAR             NOT NULL
);